{% set name = "fa2" %}
{% set version = "0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d8dcb2b6c3a53e682fb8d15ecdcbc07aaa04140fe2174fc5a90a4c41fa2de9ba

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  noarch: python

requirements:
  host:
    - pip
    - python
    - cython
  run:
    - numpy
    - python
    - scipy
    - tqdm
    - cython

test:
  imports:
    - fa2

about:
  home: https://github.com/bhargavchippada/forceatlas2
  license: GPL-3.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: The fastest ForceAtlas2 algorithm for Python (and NetworkX)

extra:
  recipe-maintainers:
    - bebatut
